export const coloumnConfig = [
    {   
        coloumnName: "Id",
        coloumnType: "regular",
        className : "col-md-2 col-12 text-break ",
        dataColoumn: "id",
        color: "#555",
        backgroundColor: "white",
        fontSize: "20px",
        linkTo: "null",
        sortExpression: "",
    },
    // {   
    //     coloumnName: "Name",
    //     coloumnType: "regular",
    //     className : "col-md-2 col-12 text-break ",
    //     dataColoumn: "Name",
    //     color: "#555",
    //     backgroundColor: "white",
    //     fontSize: "20px",
    //     linkTo: "null",
    //     sortExpression: "",
    // },
    {   
        coloumnName: "First Name",
        coloumnType: "regular",
        className : "col-md-2 col-12 text-break ",
        dataColoumn: "FirstName",
        color: "#555",
        backgroundColor: "white",
        fontSize: "20px",
        linkTo: "null",
        sortExpression: "",
    },
    
       {
        coloumnName: "Last Name",
        coloumnType: "regular",
        className : "col-md-2 col-12",
        dataColoumn: "LastName",
        color: "#555",
        fontSize: "20px",
        backgroundColor: "",
        linkTo: "null",
        sortExpression: "",
    }
]